AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - komonjo.gemspec
    - vendor/bundle/**/*
AsciiComments:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
